name: Update page
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  execute:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install hatch
        run: pip install hatch
      - name: Run script
        run: hatch run deploy
        shell: sh
